# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf

background_opacity 0.85

hide_window_decorations yes
window_padding_width 10

terminal_bell_sound no 

cursor_shape  beam

enable_lingature yes

font_size 11
#font-family jetBrains Mono
bold_font auto
italic_font auto

enable_audio_bell no

confirm_os_window_close 0
# END_KITTY_THEME
